import type { Metadata } from "next";
import { Cinzel } from "next/font/google";
import "@/app/globals.css";
import { createTheme, CssBaseline, StyledEngineProvider, ThemeProvider } from "@mui/material";

import localFont from 'next/font/local'

const amsterdam = localFont({
    src: '../fonts/Amsterdam.ttf',
    variable: '--font-amsterdam',
    display: 'swap',
    weight: '400',  
    style: 'normal',
});

const geistMono = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
    const theme = createTheme(); // Isso usa o tema padrão do MUI

    return (
        <html lang="en">
            <body className={`${amsterdam.variable} ${geistMono.variable} font-cinzel antialiased bg-slate-100`} >
                <StyledEngineProvider injectFirst>
                    <ThemeProvider theme={theme}>
                        <CssBaseline />
                        {children}
                    </ThemeProvider>
                </StyledEngineProvider>
            </body>
        </html>
    );
}
